server {
    listen 80;
    server_name _;
    client_max_body_size 2m;
    location /api/auth/ { proxy_pass http://auth:8081; include /etc/nginx/proxy_params; }
    location /api/catalog/ { proxy_pass http://catalog:8082; include /etc/nginx/proxy_params; }
    location /api/suppliers/ { proxy_pass http://supplier:8083; include /etc/nginx/proxy_params; }
    location /api/orders/ { proxy_pass http://orders:8084; include /etc/nginx/proxy_params; }
    location /api/payments/ { proxy_pass http://payment:8085; include /etc/nginx/proxy_params; }
    location /api/invoices/ { proxy_pass http://invoice:8086; include /etc/nginx/proxy_params; }
}
